name: CI Pipeline

# on:
#   push:
#     branches: [develop]

on:
  workflow_dispatch: 
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  sh_role_build_exe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout shell
      uses: actions/checkout@v3

    - name: Execute shell
      run: |
        aws iam create-role --role-name temp-admin-instance-profile --assume-role-policy-document file://role/ec2_instance_profile.json
        
  terraform_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.5

    - name: Terraform Format
      id: fmt
      run: terraform fmt

    - name: Init Terraform
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate 
  
    - name: Terraform Plan
      id: plan
      run: terraform plan

  python_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Repository
      uses: actions/checkout@v3

    - name: Lint Python
      uses: cclauss/Find-Python-syntax-errors-action@master